### ISSUE TITLE
Feature Request: CityDirectoryPhoneNumbers: Option to add phone numbers to directory entry instead of just replacing

### ISSUE THREAD

**Issue by Hunyol** [piepieonline/ShadowsOfDoubtMods#2]
as the title suggests, it would be nice to have the option to add the person/businesses phone number added to the directory instead of just replacing the address

**Comment by piepieonline** [comment]
In 1.0.4 I changed it to show citizen evidence cards, rather than just the number. I've also included an option to include the address on these cards, so that should hopefully be what you are asking for?
