### ISSUE TITLE
CityDirectoryPhoneNumbers locks the player at the beginning of The Dead of Night

### ISSUE THREAD

**Issue by Mysterius** [piepieonline/ShadowsOfDoubtMods#3]
At the beginning of the tutorial mission The Dead of Night, you have to interact with the apartment phone to look up someone (Anita Magnusson, don't know if it's fixed or not).

With the mod in v1.0.4 enabled, even with show adresses in the config, the objective doesn't trigger and you can't advance further.

**Comment by piepieonline** [comment]
Fixed in 1.0.5
