### ISSUE TITLE
Is there a list of terms SoD recognizes with citizen generator?

### ISSUE THREAD

**Issue by Zyberetro** [piepieonline/ShadowsOfDoubtMods#8]
Mainly with ethnicities as the example only lists "westEuropean" and "eastEuropean", but Shadows of Doubt obviously has more ethnicities than that (iirc).

**Comment by piepieonline** [comment]
They are included in the spreadsheet, but you need editor permissions to see them. Once you clone the spreadsheet, you'll have edit permissions on that clone. 

![image](https://github.com/user-attachments/assets/fb122fc0-a006-44ef-baf0-09893d634b38)
